### ISSUE TITLE
Regression in 2.1.3 - Crash on startup

### ISSUE THREAD

**Issue by lluni** [jheubuch/traewelling-android#263]
**Describe the bug**
Crash on startup since update from 2.1.2 to 2.1.3.

**To Reproduce**
1. (Update to 2.1.3)
2. Open Träwelldroid
3. Crash in Startup

**Expected behavior**
Not crash and function as before.

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro
 - OS: Android 10
 - Browser: Firefox
 - Version: 2.1.3 (FOSS)

**Additional context**

Error message:

```
FATAL EXCEPTION: main
Process: de.hbch.traewelling, PID: 20580
java.lang.NoClassDefFoundError: Failed resolution of: Lio/sentry/instrumentation/file/SentryFileInputStream$Factory;
	at de.hbch.traewelling.util.ExtensionsKt$readOrDownloadLineIcons$icons$1.invokeSuspend(Extensions.kt:206)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.ClassNotFoundException: io.sentry.instrumentation.file.SentryFileInputStream$Factory
	... 9 more
```

**Comment by jheubuch** [comment]
Weird behavior since I just fixed this issue via #258 

<s>I can't tell when I have time to look at this (again). Sorry. If you don't mind, I'd like to (for the moment) put you off to the last working version since there is not much free time left the next few weeks for looking at this issue.</s>

**Comment by jheubuch** [comment]
Ok so maybe I found a way to completely ban Sentry from FOSS build, I hope that works... Therefore I need your support for testing the next release 2.1.4 and checking if the crash is happening again.

**Comment by jheubuch** [comment]
You can now download the build from the [`Releases`](https://github.com/Traewelldroid/traewelldroid/releases/tag/v2.1.4) section.
Feel free to open the issue again if this is consistently occurring again.

**Comment by lluni** [comment]
2.1.4 works for me again as before. Thanks for the quick fix!
